
f = open('aa.jpg','w')
f1 = open('bb.txt','r')
f2 = open('cc.txt','a')
f3 = open('dd.txt','rb')
f4 = open('ee.txt','ab')
f5 = open('ff.txt','wb')
f6 = open('gg.txt','ab')
f7 = open('hh.txt','r+')
f8 = open('ii.txt','w+')
f9 = open('jj.txt','a+')
f10 = open('kk.txt','rb+')
f11 = open('ll.txt','wb+')
f12 = open('mm.txt','ab+')
'''
f.close()
f1.close()
f2.close()
f3.close()
f4.close()
f5.close()
f6.close()
f7.close()
f8.close()
f9.close()
f10.close()
f11.close()
f12.close()
'''
